# REFERENCE:
#  https://martinheinz.dev/blog/17
# https://github.com/MartinHeinz/python-project-blueprint/blob/master/.github/workflows/push.yml

name: Push

on:
  push:
    tags:
    - '*'

# ::setenv is a Github Actions built-in.
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Set env
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})

    - name: Log into Registry
      run: echo "${{ secrets.REGISTRY_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

    - name: Push to Github Package Registry
      run: make push VERSION=${{ env.RELEASE_VERSION }}
